"""Hubs de oposición. Solo hechos de convocatoria / portales oficiales."""

PN_TEMAS = {
    "A — Ciencias Jurídicas": [
        (1, "El Derecho: concepto y acepciones. Las normas jurídicas positivas. Jerarquía normativa. La persona en sentido jurídico. Nacionalidad, domicilio y vecindad civil."),
        (2, "La Constitución Española (I): estructura, valores, principios, derechos y deberes fundamentales. El Defensor del Pueblo."),
        (3, "La Constitución Española (II): Corona, Cortes, Gobierno, Poder Judicial, organización territorial, Tribunal Constitucional y reforma."),
        (4, "La Unión Europea. Derecho derivado. Instituciones. Cooperación policial internacional. TEDH y TJUE."),
        (5, "Organización y funcionamiento de la AGE. El Gobierno."),
        (6, "Los funcionarios públicos: concepto, clases, adquisición y pérdida de la condición."),
        (7, "El Ministerio del Interior. Secretaría de Estado de Seguridad."),
        (8, "La Dirección General de la Policía. La Policía Nacional: funciones, escalas, acceso, régimen disciplinario."),
        (9, "Ley Orgánica 2/1986 de Fuerzas y Cuerpos de Seguridad."),
        (10, "Entrada, circulación y residencia. Extranjería: estancia y residencia."),
        (11, "Infracciones en materia de extranjería y régimen sancionador."),
        (12, "Protección internacional. Menores y personas vulnerables. Apátridas y desplazados."),
        (13, "Seguridad privada en España."),
        (14, "Ley Orgánica 4/2015 de protección de la seguridad ciudadana."),
        (15, "Protección de Infraestructuras Críticas. Ciberseguridad."),
        (16, "Derecho Penal Parte General."),
        (17, "Derecho Penal Especial: homicidio, aborto, lesiones, libertad, integridad moral y libertad sexual."),
        (18, "Delitos contra el patrimonio y el orden socioeconómico."),
        (19, "Delitos contra el orden público. Armas, municiones o explosivos."),
        (20, "Delitos informáticos. Prueba digital en el proceso penal."),
        (21, "Derecho Procesal Penal. Denuncia, detención, habeas corpus, Policía Judicial."),
        (22, "Estatuto de la víctima del delito."),
        (23, "Políticas de igualdad, violencia de género, discapacidad y derechos LGTBI."),
        (24, "Introducción a la prevención de riesgos laborales."),
        (25, "Marco normativo básico en prevención de riesgos laborales."),
        (26, "Protección de datos de carácter personal. Tratamiento para fines penales."),
    ],
    "B — Ciencias Sociales": [
        (27, "Derechos Humanos. Declaración Universal, Convenio Europeo, Convención contra la Tortura."),
        (28, "Globalización y antiglobalización."),
        (29, "Actitudes y valores sociales. Estereotipos, prejuicios y discriminación."),
        (30, "Principios éticos de la sociedad actual. Delitos de odio."),
        (31, "Inmigración y movimientos migratorios."),
        (32, "Geografía humana. Demografía. Medio ambiente."),
        (33, "La seguridad. Teorías de la delincuencia."),
        (34, "Drogodependencias."),
        (35, "El desarrollo sostenible."),
        (36, "Gramática de la lengua española."),
        (37, "Ortografía de la lengua española."),
    ],
    "C — Materias técnico-científicas": [
        (38, "Fundamentos de sistemas operativos y sistemas de archivos."),
        (39, "Redes informáticas. OSI, TCP/IP, direccionamiento IP."),
        (40, "Inteligencia. OSINT. Surface, Deep y Dark Web."),
        (41, "Ciberdelincuencia y agentes de la amenaza."),
        (42, "Armas de fuego. Cartucho. Balística forense."),
        (43, "El vehículo prioritario."),
        (44, "Seguridad en la conducción de vehículos prioritarios."),
        (45, "Prevención de riesgos laborales en seguridad vial."),
    ],
}

PN_REQUISITOS = [
    ("Nacionalidad", "Tener la nacionalidad española."),
    ("Edad", "Tener 18 años cumplidos y no superar la edad máxima de jubilación en la Policía Nacional."),
    ("Antecedentes", "No haber sido condenado por delito doloso grave o menos grave, ni separado del servicio, ni inhabilitado para funciones públicas."),
    ("Cuadro médico", "No estar incluido en las causas de exclusión física o psíquica del Real Decreto 326/2021 (anexo IV de la convocatoria), con las excepciones de visión que el Tribunal Supremo dejó sin efecto."),
    ("Drogas", "No consumir drogas tóxicas, psicotrópicos o estupefacientes, salvo prescripción facultativa previa."),
    ("Armas", "Compromiso de portar armas y, en su caso, utilizarlas."),
    ("Permiso de conducir", "Permiso de la clase B, sin restricción sobre el vehículo a conducir."),
    ("Estudios", "Título de Bachiller o equivalente. Una carrera o un grado superior no suman puntos en esta Escala Básica: sirven para presentarte si equivalen, no para el test."),
    ("Idioma", "Al menos nivel A2 en inglés o francés, acreditado antes de que termine el plazo de solicitudes. Sin ese A2 no entras en el proceso."),
    ("Tropa y marinería", "Para las 541 plazas reservadas: además, cinco años de servicio como militar profesional de tropa y marinería al cierre de instancias."),
]

GC_PAGE = "https://web.guardiacivil.es/es/tramites/ingresos/ingresocuerpo/index.html"
GC_TEMARIO_PAGE = "https://web.guardiacivil.es/es/tramites/ingresos/Procedimiento-de-ingreso-directo-en-la-Escala-de-Cabos-y-Guardias-de-la-Guardia-Civil/"
PN_PORTAL = "https://www.policia.es/portalaspirantes"
PN_PORTAL_NEWS = "https://www.policia.es/portalaspirantes/web/escala-basica-ejecutiva/-/noticias-de-inter%C3%89s-para-los-opositores-y-opositoras"
INAP_AGE = "https://sede.inap.gob.es/es/procedimientos-y-servicios/seleccion/procesos-selectivos-de-cuerpos-y-escalas-generales/cuerpo-general-auxiliar-de-la-administracion-del-estado-ingreso-libre-convocatoria-2025"
JUSTICIA_AUXILIO = "https://www.mjusticia.gob.es/es/ciudadania/empleo-publico/acceso-convocatorias-perfiles/auxilio-judicial"
IIPP_WEB = "https://www.institucionpenitenciaria.es/"

HUBS = {
    "policia-nacional": {
        "name": "Policía Nacional",
        "h1": "Policía Nacional — oposición 2026",
        "eyebrow": "Escala Básica · categoría de Policía",
        "badge": "Convocatoria publicada · BOE-A-2026-15055 · En curso",
        "pages": ["requisitos", "pruebas", "fisicas", "temario", "fechas", "notas", "examenes"],
        "status": [
            ("Plazas", "2.704", "2.163 libres · 541 tropa y marinería"),
            ("Convocatoria", "Publicada", "10 de julio de 2026"),
            ("Solicitudes", "Plazo cerrado", "15 días hábiles desde el 11 de julio"),
            ("Examen", "Previsión 26 sep.", "Portal del Aspirante, acto único, salvo cambio"),
        ],
        "tiles": [
            ("calc", "Calculadora de nota", "Test de conocimientos según la base 6.1.1."),
            ("fisicas", "Pruebas físicas", "Circuito, fuerza y 1.000 m con el anexo II."),
            ("temario", "Temario", "Índice oficial del anexo I. No es el tema desarrollado."),
            ("requisitos", "Requisitos", "Edad, título, idioma A2, permiso B."),
            ("fechas", "Fechas", "BOE y previsión del Portal del Aspirante."),
            ("pruebas", "Pruebas", "De conocimientos al curso de formación."),
            ("notas", "Notas anteriores", "Corte aproximado 2025. El de 2026 aún no."),
            ("examenes", "Exámenes oficiales", "El tribunal no cuelga PDF público permanente."),
        ],
        "portal": (PN_PORTAL, "Portal del Aspirante", "Listas, citaciones y documentos oficiales."),
        "requisitos": PN_REQUISITOS,
        "requisitos_lead": "Requisitos a la fecha de fin de solicitudes, en lenguaje claro. El texto que manda es la base 2.1.1 de la convocatoria.",
        "pruebas": [
            ("Conocimientos — test de 100 preguntas, 3 opciones, 50 minutos. Mínimo 3. Solo siguen 1,75 aspirantes por plaza de turno libre.", "calc"),
            ("Aptitud física — circuito, fuerza y 1.000 m. Cero en un ejercicio elimina. Media mínima 5.", "fisicas"),
            ("Reconocimiento médico — apto o no apto.", None),
            ("Entrevista profesional y personal — apto o no apto.", None),
            ("Test psicotécnicos — apto o no apto, con el mínimo que fije el tribunal.", None),
            ("Curso de formación en la Escuela Nacional de Policía.", None),
            ("Módulo de formación práctica en puesto de trabajo.", None),
        ],
        "pruebas_lead": "Fase de oposición, luego curso y prácticas (base 1.2 y 6.1). Cada prueba enlaza a la herramienta si existe.",
        "temario": PN_TEMAS,
        "temario_lead": "Índice del anexo I. No es el temario desarrollado: no sustituye el boletín ni un manual.",
        "fechas": [
            ("Convocatoria en el BOE", "10 de julio de 2026"),
            ("Plazo de solicitudes", "15 días hábiles desde el 11 de julio de 2026. Ese plazo ya terminó."),
            ("Lista de admitidos", "Se publica en el BOE (excluidos) y consulta individual en el Portal del Aspirante."),
            (
                "Examen de conocimientos",
                "Previsión del Portal del Aspirante (18-6-2026): 26 de septiembre de 2026, acto único (conocimientos, psicotécnicos, CIB y personalidad), salvo circunstancias sobrevenidas. No está en el BOE.",
            ),
            ("Pruebas siguientes", "Las cita el tribunal en el Portal del Aspirante."),
        ],
        "fechas_lead": "Las fechas cerradas salen del BOE. La del examen es una previsión oficial del Portal del Aspirante, no una invención.",
        "notas_lead": "El mínimo 3 no es el corte. El corte de plaza lo marca el resto de aspirantes.",
        "notas": [
            ("2026", "Pendiente", "Corte de conocimientos de esta promoción", "Aún no publicado"),
            ("2025", "7,17 aproximado", "Corte de la prueba de conocimientos (promoción 42)", "Portal del Aspirante, 3-11-2025"),
        ],
        "notas_note": "No hay lista pública de todos los examinados de 2025, así que no se da un número de orden.",
        "examenes_lead": "La Policía no cuelga aquí un PDF público permanente. Los cuestionarios y plantillas salen en el Portal del Aspirante cuando el tribunal los publica.",
        "examenes": [
            {
                "year": "2026 (BAS 43)",
                "note": "El examen aún no se ha celebrado. Cuando salga, el enlace oficial estará en el Portal del Aspirante.",
                "links": [(PN_PORTAL, "Abrir Portal del Aspirante")],
            },
            {
                "year": "Años anteriores",
                "note": "Quien se examinó puede descargar plantillas desde su inscripción en el portal (acceso identificado).",
                "links": [(PN_PORTAL, "Portal del Aspirante"), (PN_PORTAL_NEWS, "Noticias oficiales BAS 43")],
            },
        ],
    },
    "guardia-civil": {
        "name": "Guardia Civil",
        "h1": "Guardia Civil — oposición 2026",
        "eyebrow": "Escala de Cabos y Guardias",
        "badge": "Convocatoria BOE-A-2026-9982 · Psicofísicas en curso",
        "pages": ["requisitos", "pruebas", "temario", "fechas", "notas", "examenes"],
        "status": [
            ("Plazas", "3.240", "1.704 libres · 1.296 tropa · 240 Colegio"),
            ("Convocatoria", "Publicada", "8 de mayo de 2026"),
            ("Solicitudes", "Cerradas", "Hasta el 1 de junio de 2026"),
            ("Conocimientos", "11 jul. 2026", "Ya celebrado. Psicofísicas: 2–26 sep."),
        ],
        "tiles": [
            ("calc", "Calculadora de nota", "Ortografía, gramática, conocimientos, inglés y psicotécnico."),
            ("examenes", "Exámenes oficiales", "2026, 2025 y 2022 (por día y Canarias)."),
            ("temario", "Temario", "25 temas oficiales. Índice, no el tema desarrollado."),
            ("requisitos", "Requisitos", "Edad, ESO o equivalente, permiso B."),
            ("fechas", "Fechas", "Proceso actual en la web de la Guardia Civil."),
            ("pruebas", "Pruebas", "De las escritas a las psicofísicas y la academia."),
            ("notas", "Notas anteriores", "Último propuesto a alumno 2025, turno libre."),
        ],
        "portal": (GC_PAGE, "Proceso oficial 2026", "Resultados, citaciones y documentos de la Jefatura de Enseñanza."),
        "requisitos": [
            ("Nacionalidad", "Tener la nacionalidad española."),
            ("Edad", "Cumplir 18 años en 2026 y no cumplir 41 durante 2026."),
            ("Estudios", "ESO o un requisito equivalente para acceder a FP de grado medio (base 2.1.9). No exige Bachiller."),
            ("Permiso de conducir", "Permiso de la clase B."),
            ("Antecedentes y derechos", "Sin antecedentes penales, con derechos civiles y sin separación e inhabilitación firmes."),
            ("Proceso penal", "No estar procesado, investigado o acusado por delito doloso con apertura de juicio oral."),
            ("Armas", "Compromiso de portar armas y, en su caso, utilizarlas."),
            ("Tatuajes", "Sin tatuajes contrarios a valores constitucionales, disciplina o imagen del Cuerpo."),
            ("Aptitud", "Superar el reconocimiento médico y las pruebas psicofísicas de esta convocatoria."),
            ("Tropa y marinería", "Para las 1.296 plazas reservadas: cinco años de servicio y compromiso no finalizado al cierre de instancias."),
        ],
        "requisitos_lead": "Requisitos de la base 2.1, en lenguaje claro. El texto que manda es el BOE.",
        "pruebas": [
            ("Ortografía — apto o no apto. 6 o más errores eliminan.", "calc"),
            ("Gramática — apto o no apto. 6 o más errores eliminan.", "calc"),
            ("Conocimientos generales — 100 preguntas. Mínimo 50.", "calc"),
            ("Lengua inglesa — 20 preguntas. Mínimo 8.", "calc"),
            ("Aptitudes intelectuales — 80 preguntas, máximo 30. Mínimo 12.", "calc"),
            ("Concurso — méritos del apéndice I, hasta 45. Aquí se introduce el total ya baremado.", "calc"),
            ("Pruebas físicas — 2.000 m, circuito, extensiones de brazos y 50 m de natación.", None),
            ("Entrevista personal y reconocimiento médico.", None),
            ("Formación en la Academia de Guardias (Baeza) y prácticas en unidad.", None),
        ],
        "pruebas_lead": "Concurso-oposición (bases 5 y 6). Las escritas ya se celebraron el 11 de julio de 2026. Las psicofísicas van del 2 al 26 de septiembre.",
        "temario": {
            "Temario oficial (25 temas)": [
                (1, "Derechos humanos."),
                (2, "Igualdad efectiva de mujeres y hombres."),
                (3, "Prevención de riesgos laborales."),
                (4, "Derecho constitucional."),
                (5, "Derecho de la Unión Europea."),
                (6, "Instituciones internacionales."),
                (7, "Derecho civil."),
                (8, "Derecho penal."),
                (9, "Derecho procesal penal."),
                (10, "Derecho administrativo."),
                (11, "Protección de datos."),
                (12, "Extranjería e inmigración."),
                (13, "Seguridad pública y seguridad privada."),
                (14, "Ministerio del Interior. Ministerio de Defensa."),
                (15, "Fuerzas y Cuerpos de Seguridad. Guardia Civil."),
                (16, "Materias socio-culturales. Protección civil. Desarrollo sostenible. Eficiencia energética."),
                (17, "Materias técnico-científicas. Tecnologías de la información y la comunicación."),
                (18, "Topografía."),
                (19, "Deontología profesional."),
                (20, "Responsabilidad penal de los menores."),
                (21, "Protección integral contra la violencia de género."),
                (22, "Armas y explosivos."),
                (23, "Derecho fiscal."),
                (24, "Inglés."),
                (25, "Lengua española (ortografía y gramática)."),
            ]
        },
        "temario_lead": "Títulos oficiales de la web de la Guardia Civil (Resolución de 26 de junio de 2019, modificada). No es el temario desarrollado.",
        "fechas": [
            ("Convocatoria en el BOE", "8 de mayo de 2026 (BOE-A-2026-9982)."),
            ("Plazo de solicitudes", "Cerrado el 1 de junio de 2026 a las 23:59."),
            ("Admitidos definitivos", "Resolución 160/38308/2026, de 30 de junio."),
            ("Pruebas escritas", "11 de julio de 2026."),
            ("Resultado definitivo escritas", "Resolución del Tribunal de 24 de julio de 2026."),
            ("Pruebas psicofísicas", "Del 2 al 26 de septiembre de 2026 en el Colegio de Guardias Jóvenes de Valdemoro. Cada aspirante tiene día asignado."),
        ],
        "fechas_lead": "Calendario de la página oficial de ingreso, actualizada el 24 de julio de 2026.",
        "notas_lead": "No hay un «corte de plaza» inventado. Lo que hay es la lista BOE de quienes sí obtuvieron plaza el año pasado.",
        "notas": [
            ("2026", "Pendiente", "Lista de propuestos a alumno de esta convocatoria", "Aún no publicada"),
            ("2025", "89,61 último de la lista", "Último propuesto a alumno, turno libre (total del proceso)", "BOE-A-2025-21403"),
        ],
        "notas_note": "Esa cifra es el total de quien cerró la lista de plaza en 2025, no el ranking de todos los examinados ni tu puesto de 2026. Hay que haber superado también el resto de pruebas.",
        "examenes_lead": "Cuestionarios y plantillas de la Jefatura de Enseñanza. La plantilla válida es la del PDF nº 2 (corrige la pregunta 7 del modelo A y la 88 del B).",
        "examenes": [
            {
                "year": "2026 (11 de julio)",
                "note": "Pruebas de conocimientos teórico-prácticos: ortografía, gramática, conocimientos e inglés.",
                "links": [
                    ("https://web.guardiacivil.es/export/sites/guardiaCivil/documentos/pdfs/2026/Procesos_Selectivos_2026/INGRESO-GC-2026-TIPO-A.pdf", "Examen modelo A"),
                    ("https://web.guardiacivil.es/export/sites/guardiaCivil/documentos/pdfs/2026/Procesos_Selectivos_2026/INGRESO-GC-2026-TIPO-B.pdf", "Examen modelo B"),
                    ("https://web.guardiacivil.es/export/sites/guardiaCivil/documentos/pdfs/2026/Procesos_Selectivos_2026/PLANTILLAS-INGRESO-CABOS-Y-GUARDIAS.-2026.pdf", "Plantilla de respuestas (PDF nº 2)"),
                    (GC_PAGE, "Página oficial del proceso"),
                ],
            },
            {
                "year": "2025",
                "note": "Convocatoria anterior (Resolución 160/38240/2025). Sirve para practicar, no para la fórmula de 2026.",
                "links": [
                    ("https://web.guardiacivil.es/export/sites/guardiaCivil/documentos/pdfs/2025/Procesos_Selectivos_2025/IngresoGC_2025/INGRESO-GC-2025-TIPO-B-.pdf", "Examen modelo B"),
                    (GC_PAGE, "Archivo en la web de la Guardia Civil"),
                ],
            },
        ],
    },
    "auxiliar-age": {
        "name": "Auxiliar AGE",
        "h1": "Auxiliar AGE — oposición 2026",
        "eyebrow": "Cuerpo General Auxiliar · ingreso libre",
        "badge": "Convocatoria BOE-A-2025-26262 · Examen ya celebrado",
        "pages": ["requisitos", "pruebas", "temario", "fechas", "notas", "examenes"],
        "status": [
            ("Plazas", "1.700", "156 reserva discapacidad"),
            ("Convocatoria", "Publicada", "22 de diciembre de 2025"),
            ("Solicitudes", "Cerradas", "23 dic. 2025 – 22 ene. 2026"),
            ("Examen", "23 may. 2026", "Ejercicio único. Plantillas en el INAP"),
        ],
        "tiles": [
            ("calc", "Calculadora de nota", "Puntuación directa 60+50. Sin transformada inventada."),
            ("examenes", "Exámenes oficiales", "Cuestionarios, plantillas y aulas por ciudad."),
            ("temario", "Temario", "Programa del anexo I, bloques I y II."),
            ("requisitos", "Requisitos", "Nacionalidad, ESO o equivalente."),
            ("fechas", "Fechas", "Lo publicado por INAP y BOE."),
            ("pruebas", "Pruebas", "Un ejercicio, dos partes."),
            ("notas", "Notas anteriores", "Sin corte de plaza inventado."),
        ],
        "portal": (INAP_AGE, "Sede INAP — ingreso libre 2025", "Admitidos, cuestionarios y plantillas oficiales."),
        "requisitos": [
            ("Nacionalidad", "Española, o las situaciones de la base 3.2 (UE, cónyuge, etc.)."),
            ("Edad", "Tener 16 años y no superar la edad máxima de jubilación forzosa."),
            ("Estudios", "Graduado en ESO o equivalente / título superior. Es el C2, no exige Bachiller."),
            ("Capacidad", "Capacidad funcional para el desempeño de las tareas."),
            ("Habilitación", "No separado del servicio ni inhabilitado para empleo público."),
        ],
        "requisitos_lead": "Requisitos de las normas comunes y del anexo I (ingreso libre). El texto que manda es el BOE.",
        "pruebas": [
            ("Primera parte — hasta 60 preguntas (30 de temario y 30 psicotécnicas) más 5 de reserva.", "calc"),
            ("Segunda parte — hasta 50 preguntas de ofimática (Windows 11 y Microsoft 365) más 5 de reserva.", "calc"),
            ("Todo en una sesión de 90 minutos. Cada error resta un tercio. Las blancas no restan.", "calc"),
            ("La nota 0–50 de cada parte es transformada por la CPS. Aquí se muestra la puntuación directa.", "calc"),
        ],
        "pruebas_lead": "Ejercicio único del anexo I. Las dos partes son obligatorias y eliminatorias.",
        "temario": {
            "I. Organización pública": [
                (1, "La Constitución Española de 1978."),
                (2, "El Tribunal Constitucional. La reforma. La Corona."),
                (3, "Las Cortes Generales. El Defensor del Pueblo."),
                (4, "El Poder Judicial. El Tribunal Supremo."),
                (5, "El Gobierno y la Administración."),
                (6, "Gobierno Abierto. Agenda 2030."),
                (7, "Ley 19/2013 de transparencia y buen gobierno."),
                (8, "La Administración General del Estado."),
                (9, "Organización territorial del Estado."),
                (10, "La Unión Europea."),
                (11, "Procedimiento administrativo común y recurso contencioso-administrativo."),
                (12, "Protección de datos personales."),
                (13, "Personal funcionario: clases, selección, provisión y situaciones."),
                (14, "Derechos, deberes, carrera, retribuciones y régimen disciplinario."),
                (15, "El presupuesto del Estado."),
                (16, "Igualdad, LGTBI, discapacidad y dependencia."),
            ],
            "II. Actividad administrativa y ofimática": [
                (1, "Atención al público."),
                (2, "Servicios de información administrativa."),
                (3, "Documento, registro y archivo."),
                (4, "Administración electrónica y servicios al ciudadano."),
                (5, "Informática básica."),
                (6, "Entorno Windows."),
                (7, "Explorador de Windows."),
                (8, "Word 365."),
                (9, "Excel 365."),
                (10, "Access 365."),
                (11, "Outlook 365."),
                (12, "Internet."),
            ],
        },
        "temario_lead": "Programa del punto 5 del anexo I. Índice oficial, no el temario desarrollado.",
        "fechas": [
            ("Convocatoria en el BOE", "22 de diciembre de 2025 (BOE-A-2025-26262)."),
            ("Plazo de solicitudes", "Del 23 de diciembre de 2025 al 22 de enero de 2026."),
            ("Examen", "23 de mayo de 2026 (ejercicio único)."),
            ("Plantillas provisionales", "Publicadas por el INAP el 25 de mayo de 2026 en su sede electrónica."),
        ],
        "fechas_lead": "Solo fechas de la convocatoria o de la sede del INAP.",
        "notas_lead": "El 25 transformado de cada parte lo fija la CPS. Esta web no inventa ese umbral ni un corte de plaza.",
        "notas": [
            ("2025/26", "Pendiente", "Lista de aprobados / corte de esta convocatoria", "Cuando lo publique el INAP o el BOE"),
        ],
        "notas_note": "Sin lista comparable publicada aquí. No se fabrica un histórico.",
        "examenes_lead": "Los cuestionarios y plantillas oficiales están en la ficha del INAP, no en un blog.",
        "examenes": [
            {
                "year": "Convocatoria 2025 (examen 23-5-2026)",
                "note": "Ingreso libre. Modelos A y B y plantillas provisionales en la sede del INAP.",
                "links": [
                    (INAP_AGE, "Cuestionarios y plantillas en el INAP"),
                    ("https://www.boe.es/diario_boe/txt.php?id=BOE-A-2025-26262", "Convocatoria en el BOE"),
                ],
            }
        ],
    },
    "auxilio-judicial": {
        "name": "Auxilio Judicial",
        "h1": "Auxilio Judicial — oposición 2026",
        "eyebrow": "Administración de Justicia · acceso libre",
        "badge": "Convocatoria BOE-A-2025-27053 · En curso",
        "pages": ["requisitos", "pruebas", "temario", "fechas", "notas", "examenes"],
        "status": [
            ("Plazas", "425", "Acceso libre, Orden PJC/1549/2025"),
            ("Convocatoria", "Publicada", "30 de diciembre de 2025"),
            ("Solicitudes", "Cerradas", "Según el plazo de la orden"),
            ("Examen", "Por anunciar", "Tras la lista definitiva de admitidos"),
        ],
        "tiles": [
            ("calc", "Calculadora de nota", "0,60/−0,15 y 1/−0,25. No es la penalización de la AGE."),
            ("temario", "Temario", "26 temas del anexo VI.c)."),
            ("requisitos", "Requisitos", "Nacionalidad española y ESO o equivalente."),
            ("pruebas", "Pruebas", "Teórico y práctico el mismo día."),
            ("fechas", "Fechas", "Lo que fija la orden y el BOE."),
            ("examenes", "Exámenes oficiales", "A/B, incidencias y prueba adicional del ministerio."),
            ("notas", "Notas anteriores", "Sin corte inventado de esta convocatoria."),
        ],
        "portal": (JUSTICIA_AUXILIO, "Empleo público · Auxilio Judicial", "Acuerdos del tribunal y documentos del ministerio."),
        "requisitos": [
            ("Nacionalidad", "Tener la nacionalidad española."),
            ("Estudios", "Graduado en ESO o equivalente."),
            ("Edad", "Tener 16 años y no superar la edad de jubilación forzosa."),
            ("Capacidad", "Capacidad funcional para las tareas del cuerpo."),
            ("Habilitación", "No separado del servicio ni inhabilitado para empleo público."),
        ],
        "requisitos_lead": "Requisitos de la Orden PJC/1549/2025. El texto que manda es el BOE.",
        "pruebas": [
            ("Primer ejercicio (teórico) — 100 preguntas, 4 reservas. 0,60 por acierto y −0,15 por error. Mínimo 30.", "calc"),
            ("Segundo ejercicio (práctico) — 40 preguntas, 2 reservas. 1 por acierto y −0,25 por error. Mínimo 20.", "calc"),
            ("Los dos el mismo día. Superar 30 y 20 no es plaza: la lista se recorta al número de plazas.", "calc"),
        ],
        "pruebas_lead": "Anexo V.a). Justicia no usa la penalización 1/3 de la AGE.",
        "temario": {
            "Anexo VI.c) — Auxilio Judicial": [
                (1, "La Constitución española de 1978. Corona, Cortes y Tribunal Constitucional."),
                (2, "Igualdad, violencia de género, igualdad de trato y derechos LGTBI."),
                (3, "Gobierno y Administración. Secretaría de Estado de Justicia."),
                (4, "Organización territorial del Estado."),
                (5, "La Unión Europea."),
                (6, "El Poder Judicial. CGPJ. Independencia judicial. Ministerio Fiscal."),
                (7, "Tribunal Supremo, Audiencia Nacional, TSJ y Audiencias Provinciales."),
                (8, "Tribunales de Instancia y jueces de paz."),
                (9, "Carta de Derechos de los Ciudadanos ante la Justicia. Justicia gratuita."),
                (10, "Oficina judicial, Tribunales de Instancia y nuevas tecnologías."),
                (11, "El Letrado de la Administración de Justicia."),
                (12, "Cuerpos de funcionarios al servicio de la Administración de Justicia."),
                (13, "Cuerpos Generales (I): acceso, derechos y jornada."),
                (14, "Cuerpos Generales (II): situaciones, provisión y régimen disciplinario."),
                (15, "Libertad sindical, huelga y prevención de riesgos laborales."),
                (16, "Procedimientos declarativos en la LEC."),
                (17, "Ejecución civil. Embargo, lanzamiento y depósitos."),
                (18, "Procedimientos penales en la LECrim."),
                (19, "Procedimientos contencioso-administrativos."),
                (20, "El proceso laboral."),
                (21, "Los actos procesales: lugar, tiempo y forma."),
                (22, "Resoluciones judiciales y del LAJ."),
                (23, "Oficios, mandamientos, exhortos y cooperación internacional."),
                (24, "Notificaciones, citaciones y emplazamientos."),
                (25, "El Registro Civil."),
                (26, "Archivo judicial y expurgo."),
            ]
        },
        "temario_lead": "Títulos del anexo VI.c) de la Orden PJC/1549/2025. Índice, no el tema desarrollado.",
        "fechas": [
            ("Convocatoria en el BOE", "30 de diciembre de 2025 (BOE-A-2025-27053)."),
            ("Examen de esta convocatoria", "Se anuncia en el BOE tras la lista definitiva de admitidos, dentro de los 45 días siguientes."),
        ],
        "fechas_lead": "El día del examen de esta orden aún no está en el BOE. No se estima aquí.",
        "notas_lead": "Los mínimos 30 y 20 no son el corte de plaza.",
        "notas": [
            ("2026", "Pendiente", "Corte / lista de esta Orden PJC/1549/2025", "Aún no publicado"),
        ],
        "notas_note": "No se copia un corte de otra convocatoria.",
        "examenes_lead": "Los PDF del ministerio son de procesos concretos. El de 2025 (Orden PJC/1437/2024) no es el examen de esta convocatoria.",
        "examenes": [
            {
                "year": "Esta convocatoria (PJC/1549/2025)",
                "note": "Cuando el tribunal publique cuestionarios, el enlace oficial estará en la ficha de Auxilio Judicial del ministerio.",
                "links": [
                    (JUSTICIA_AUXILIO, "Ficha oficial de Auxilio Judicial"),
                    ("https://www.boe.es/diario_boe/txt.php?id=BOE-A-2025-27053", "Convocatoria en el BOE"),
                ],
            },
            {
                "year": "Convocatoria anterior (examen 27-9-2025)",
                "note": "Orden PJC/1437/2024. Sirve para practicar el formato, no para esta nota.",
                "links": [
                    (
                        "https://www.mjusticia.gob.es/es/Ciudadano/EmpleoPublico/Documents/Acuerdo%20del%20TCU%20Auxilio%20Judicial-%20plantilla%20definitiva-%20examen%2027%20de%20septiembre%20de%202025%20-.pdf",
                        "Acuerdo y plantilla definitiva del TCU",
                    ),
                    (JUSTICIA_AUXILIO, "Más documentos en el ministerio"),
                ],
            },
        ],
    },
    "ayudantes-iipp": {
        "name": "Ayudantes IIPP",
        "h1": "Ayudantes IIPP — oposición 2026",
        "eyebrow": "Cuerpo de Ayudantes de Instituciones Penitenciarias",
        "badge": "Convocatoria BOE-A-2026-13226 · Examen anunciado",
        "pages": ["requisitos", "pruebas", "temario", "fechas", "notas", "examenes"],
        "status": [
            ("Plazas", "1.050", "Acceso libre, subgrupo C1"),
            ("Convocatoria", "Publicada", "18 de junio de 2026"),
            ("Solicitudes", "Cerradas", "20 días hábiles desde el 19 de junio"),
            ("Examen", "25 oct. 2026", "BOE-A-2026-17631. Madrid y Las Palmas"),
        ],
        "tiles": [
            ("calc", "Calculadora de nota", "Puntuación directa 120+40. Sin umbral inventado."),
            ("temario", "Temario", "Programa oficial del BOE, por bloques."),
            ("requisitos", "Requisitos", "Nacionalidad española y Bachiller o Técnico."),
            ("pruebas", "Pruebas", "Test, supuestos y reconocimiento médico."),
            ("fechas", "Fechas", "Primer ejercicio: 25 de octubre de 2026."),
            ("examenes", "Exámenes oficiales", "Plantillas de Interior. Madrid y Las Palmas, mismo test."),
            ("notas", "Notas anteriores", "Sin corte inventado."),
        ],
        "portal": (
            "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-17631",
            "Admitidos y fecha de examen",
            "Resolución de 5 de agosto de 2026.",
        ),
        "requisitos": [
            ("Nacionalidad", "Tener la nacionalidad española."),
            ("Estudios", "Título de Bachiller o Técnico, o estar en condiciones de obtenerlo al cierre de instancias."),
            ("Edad", "Tener 16 años y no superar la edad de jubilación forzosa."),
            ("Capacidad", "Capacidad funcional para las tareas del cuerpo."),
            ("Habilitación", "No separado del servicio ni inhabilitado para empleo público."),
        ],
        "requisitos_lead": "Base 3 de BOE-A-2026-13226. El texto que manda es el boletín.",
        "pruebas": [
            ("Primera parte — 120 preguntas, 3 de reserva, 1 h 45 min. Cada error resta un tercio.", "calc"),
            ("Segunda parte — 8 supuestos de 5 preguntas (40). Solo se corrige si superaste 10 en la escala transformada de la primera.", "calc"),
            ("Reconocimiento médico — apto o no apto, hasta el número de plazas.", None),
            ("Curso selectivo y prácticas. La «No apto» o no presentarse excluye.", None),
        ],
        "pruebas_lead": "El 10 de las bases es de la escala 0–20, no de la puntuación directa. Sin el umbral de este tribunal no se afirma ese 10.",
        "temario": {
            "Primera parte — Organización del Estado, personal y gestión": [
                (1, "La Constitución Española de 1978."),
                (2, "El Poder Judicial. Tribunal Constitucional. Ministerio Fiscal."),
                (3, "El Gobierno y la Administración periférica."),
                (4, "Organización territorial. Competencias autonómicas en materia penitenciaria."),
                (5, "La Unión Europea."),
                (6, "Ministerio del Interior. Secretaría General de IIPP."),
                (7, "Personal de IIPP. Cuerpo de Ayudantes: funciones."),
                (8, "EBEP. Incompatibilidades y régimen disciplinario."),
                (9, "Acceso al empleo público. Situaciones administrativas."),
                (10, "Contratos del sector público."),
                (11, "Ley del Voluntariado."),
                (12, "Políticas de igualdad, violencia de género, discapacidad y dependencia."),
                (13, "Gobierno abierto y transparencia."),
                (14, "Actividad de las Administraciones Públicas. Silencio administrativo."),
                (15, "Fuentes del Derecho Administrativo. Acto y recursos."),
                (16, "Procedimiento administrativo común y sancionador."),
                (17, "El presupuesto del Estado."),
            ],
            "Segunda parte — Derecho Penal": [
                (1, "Derecho Penal: concepto, fuentes y garantías."),
                (2, "Delitos, grados de ejecución y circunstancias modificativas."),
                (3, "Penas. Prisión permanente revisable."),
                (4, "Suspensión, trabajos en beneficio de la comunidad y medidas de seguridad."),
                (5, "Homicidio, lesiones, violencia de género, patrimonio, libertad y tráfico de drogas."),
                (6, "Torturas, libertad sexual, honor, falsedades e intrusismo."),
                (7, "Delitos contra la Administración Pública."),
                (8, "Delitos contra la Administración de Justicia y garantías constitucionales."),
                (9, "El proceso penal y las medidas cautelares."),
                (10, "Procedimiento ordinario, abreviado y habeas corpus. Recursos."),
            ],
            "Segunda parte — Derecho Penitenciario": [
                (1, "Normativa supranacional penitenciaria."),
                (2, "Derecho Penitenciario y artículo 25.2 CE."),
                (3, "Relación jurídico-penitenciaria. Derechos y deberes de los internos."),
                (4, "Prestaciones: sanidad, higiene, religión y acción social."),
                (5, "Régimen: ingreso, comunicaciones y traslados."),
                (6, "Seguridad interior y exterior. Medios coercitivos."),
                (7, "Tipos de establecimientos. Régimen ordinario y preventivos."),
                (8, "Régimen cerrado y abierto."),
                (9, "Tratamiento (1): clasificación y observación."),
                (10, "Tratamiento (2): programas, formación y deporte."),
                (11, "Relación laboral en prisión. Trabajo penitenciario."),
                (12, "Permisos de salida."),
                (13, "Libertad, expulsión y libertad condicional."),
                (14, "Formas especiales de ejecución y medidas alternativas."),
                (15, "Régimen disciplinario."),
                (16, "Juez de Vigilancia Penitenciaria."),
                (17, "Modelo organizativo: órganos colegiados y unipersonales."),
                (18, "Régimen administrativo (1): expediente del interno."),
                (19, "Régimen administrativo (2): servicio interior e identificación."),
                (20, "Régimen económico, peculio y habilitación."),
            ],
            "Segunda parte — Conducta humana": [
                (1, "Elementos de la conducta humana y técnicas de evaluación."),
                (2, "Organización social de la prisión y efectos de la reclusión."),
                (3, "Habilidades sociales y conducta adictiva en prisión."),
            ],
        },
        "temario_lead": "Programa del BOE-A-2026-13226. Índice oficial, no el temario desarrollado.",
        "fechas": [
            ("Convocatoria en el BOE", "18 de junio de 2026 (BOE-A-2026-13226)."),
            ("Plazo de solicitudes", "20 días hábiles desde el 19 de junio de 2026. Ya cerrado."),
            ("Admitidos provisionales", "Resolución de 5 de agosto de 2026 (BOE-A-2026-17631)."),
            ("Primer ejercicio", "25 de octubre de 2026. Universidad Complutense de Madrid, 9:00 (peninsular); Universidad de Las Palmas de Gran Canaria, 8:00 (insular)."),
        ],
        "fechas_lead": "La fecha del primer ejercicio está en el BOE, no es una estimación de academia.",
        "notas_lead": "Sin umbral transformado de este tribunal no hay un 10 sobre 20 ni un corte de plaza.",
        "notas": [
            ("2026", "Pendiente", "Notas y lista de esta convocatoria", "Aún no publicadas"),
        ],
        "notas_note": "No se usa el umbral de 2025 como si ya valiera para 2026.",
        "examenes_lead": "El primer ejercicio es el 25 de octubre de 2026. Los cuestionarios saldrán en Interior / IIPP cuando el tribunal los publique.",
        "examenes": [
            {
                "year": "2026",
                "note": "Aún no hay cuestionario. Fuente de la fecha: BOE-A-2026-17631.",
                "links": [
                    ("https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-17631", "Fecha y admitidos en el BOE"),
                    ("https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-13226", "Convocatoria"),
                    (IIPP_WEB, "Secretaría General de IIPP"),
                ],
            }
        ],
    },
}
